# Generated by Django 5.1 on 2024-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Joshua', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='genre',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
