# Generated by Django 5.1 on 2024-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_role_alter_profile_genre_track_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatorlabelprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('curator', 'Curator/Label')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ArtistProfile',
        ),
        migrations.DeleteModel(
            name='CuratorLabelProfile',
        ),
    ]
