# Generated by Django 5.1 on 2024-08-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_profile_social_media_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tracks',
            field=models.ManyToManyField(related_name='campaigns', to='core.track'),
        ),
    ]
