# Generated by Django 5.1 on 2024-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_amazon_music_link_profile_apple_music_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_tracks',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core.track'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('curator', 'Curator/Label'), ('fan', 'Fan')], max_length=50, null=True),
        ),
    ]
